<header>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="navbar-brand" href="/home"><img alt="Logo" src="/resources/images/cards-1-512.png" height="32px"></a>
                <a class="nav-item nav-link
                   <?= strpos($_SERVER['REQUEST_URI'], "home") ? "active" : "" ?>"
                   href="/home">Home</a>
                <? if(isset($_SESSION['USER_ID'])): ?>
                    <!-- Logged In -->
                    <a class="nav-item nav-link
                       <?= strpos($_SERVER['REQUEST_URI'], "game") ? "active" : "" ?>"
                       href="/game-overview">Games</a>
                    <a class="nav-item nav-link
                        <?= strpos($_SERVER['REQUEST_URI'], "profile") ? "active" : "" ?>"
                       href="/profile">My Profile</a>
                    <a class="nav-item nav-link" href="/logout">Logout</a>
                <?php else: ?>
                    <!-- Not logged in -->
                    <a class="nav-item nav-link
                        <?= strpos($_SERVER['REQUEST_URI'], "register") ? "active" : "" ?>"
                       href="/register">Register</a>
                    <a class="nav-item nav-link
                        <?= strpos($_SERVER['REQUEST_URI'], "login") ? "active" : "" ?>"
                       href="/login">Login</a>
                <?php endif; ?>

            </div>
        </div>
    </nav>
</header>