<!-- Needed on every page -->
<title><?= isset($pageTitle) ? $pageTitle : "Planning Poker"?></title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<script type="text/javascript" src="/resources/assets/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/views/shared/alert/alert.js"></script>
<script type="text/javascript" src="/requests/HttpRequest.js"></script>
<link href="/resources/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="/views/shared/header/header.css" rel="stylesheet">
<link href="/views/shared/footer/footer.css" rel="stylesheet">
<link href="/views/shared/shared.css" rel="stylesheet">