<!DOCTYPE html>
<html lang="en">
<head>
    <script type="text/javascript" src="/resources/assets/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/resources/assets/jqueryui/jquery-ui.js"></script>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
    <script type="text/javascript" src="/views/game-overview/game-overview.js"></script>
</head>
<body>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/header/header.phtml" ?>
    <div class="container min-vh-80">
        <h1><?php if( isset($pageTitle)) echo($pageTitle)?></h1><br/>
        <a id="game-overview-create-button" href="/game-create" class="btn btn-primary mb-5">Create Game</a>
        <input id="game-overview-search" type="text" placeholder="Search.." class="form-control mb-3">

        <div id="game-overview-cards" class="row">
            <?php
            if (isset($games)):
                foreach ($games as $game) { ?>
                    <div class="col-6 game-overview-filter">
                        <div class="card m-2" style="width: 100%;">
                            <div class="card-body">
                                <h5 id="game-overview-card-title" class="card-title"><?=$game->title?></h5>
                                <p id="game-overview-card-description" class="card-text"><?=$game->description?></p>
                                <a href="/game-play?game_id=<?=$game->game_id?>" class="btn btn-primary">Join Game</a>
                            </div>
                        </div>
                    </div>
                <?php }
            endif;
            ?>
        </div>
    </div>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/footer/footer.phtml" ?>
</body>
<html>