<html>
<head>
    <title>404 Not Found</title>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
</head>
<body>
<?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/header/header.phtml" ?>
<div class="container min-vh-80">
    <div class="container text-center">
        <h2>404 Not Found</h2>
        <h4>There's nothing here!</h4>
    </div>
</div>
<?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/footer/footer.phtml" ?>
</body>
</html>