<html>
    <head>
        <title>500 Internal Error</title>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
    </head>
    <body>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/header/header.phtml" ?>
        <div class="container min-vh-80">
            <div class="container">
                <h2 class="text-center">500 Internal Error</h2>
                <p>
                    A fatal error occured:
                    <?php
                    if (isset($isMessage) && $isMessage) {
                        echo $_SESSION['INTERNAL_ERROR'];
                    } else {
                        echo "No additional information was given.";
                    }
                    $_SESSION['INTERNAL_ERROR'] = null;
                    ?>
                    <br/>
                    Please contact the local site administrator with information on how to replicate this.<br/><br/>
                    <a href="/">Back to home</a>
                </p>
            </div>
        </div>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/footer/footer.phtml" ?>
    </body>
</html>
