<!DOCTYPE html>
<html lang="en">
<head>
    <script type="text/javascript" src="/resources/assets/jquery/jquery.min.js"></script>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
    <script type="text/javascript" src="/views/game-play/game-play.js"></script>
</head>
<body>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/header/header.phtml" ?>
    <div class="container min-vh-80">

    </div>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/footer/footer.phtml" ?>
</body>