<!DOCTYPE html>
<html>
    <head>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
    </head>
    <body>
        <div class="container min-vh-80 d-flex justify-content-center align-middle">
            <div class="col-lg-8">
                <div class="card mt-5">
                    <div class="card-body text-center">
                        <h1 class="card-title">Login</h1>
                        <h3 class="card-text">Planning Poker</h3>

                        <?php if(isset($isError) && $isError): ?>
                            <div class="alert alert-danger" role="alert">
                                <p class="text-danger"><?php echo $_SESSION['LOGIN_ERROR']; ?></p>
                            </div>
                        <?php endif ?>

                        <form class="mt-4" method="post">
                            <div class="form-group">
                                <input type="text" class="form-control" name="emailOrId" placeholder="Username/E-Mail"
                                       maxlength="32" required>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" name="password" placeholder="Password" maxlength="32" required>
                            </div>
                            <div>
                                <button type="submit" class="btn btn-primary" name="login">Login</button>
                            </div>
                        </form>
                        <div class="mt-3">
                            <a href="/register">Register</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
